### ISSUE TITLE
Photo preview shows completely wrong photos 

### ISSUE THREAD

**Issue by teilzeitutopist** [ente-io/photos-app#1279]
**describe the bug**
I am using ente.io on the same account with my significant other. We both take photos with our smartphones that are uploaded to the same folder on ente.io. So each of us can see the photos of the other person in the app. 
The bug: I took about ten photos a few days ago and my significant other sees completely different photos. The photos shown are two year old photos sent by someone else via WhatsApp. The "Details" screen in ente shows the original file name and date as well as size. "Download" is not shown as the (wrongly associated) file is already on the device. 
That WhatsApp folder is not part of any sync tasks in the Ente-app and the photos are named completely different, have a different size etc. I suppose ente.io has some kind of of matching mechanism (hash or something) for the comparison with locally stored files that is not reliable in identifying photos correctly. 

**To Reproduce**
I have no idea how to reproduce. 

**Expected behavior**
I want to see the correct pictures taken on another device. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Pixel 5 (photos taken), Pixel 6a (showing wrong photos) 
 - OS: CalyxOS 4.11 (Android  13) (both) 
 - App Version: 0.7.77 (both)

**Comment by ua741** [comment]
Hey,

Thank you for the detailed report. 

Can you please initiate a bug report from the app (`Settings`->`Support`->`Report a bug`). Double tap on `Report a bug` if you email client is not able to attach the logs. In the email, please let us know one or two files names as well for which you are seeing this issue.

Regarding matching a uploaded file to local file, there are primarily two scenarios:
 1) While syncing remote file to the device, we match it to a local file if both remote File and local file have same (localFileIdentifer, deviceFolder, fileName, fileType). 

 2) During upload of a local file, we check (on device) if there's already an uploaded file with same hash and fileType. If there's a match, we link the local file to the remote file.
 
 Based on you detailed report, neither of these two logic should result in the incorrect match because
 1) Both file & device folder name are different.
 2) The local file is not marked for backup.


---

After you report, I took another look at the code. I can see one potential bug that can result in incorrect mapping in certain cases.  But again, it should not really map to such an old file. We will anyways patch that issue.

**Comment by teilzeitutopist** [comment]
Thanks, I did that today.
