### ISSUE TITLE
Misaligned icon in detail view

### ISSUE THREAD

**Issue by BuzzKnightbeer** [ente-io/photos-app#1386]
When viewing the detail view of a picture, the heart icon in the top right is not aligned with the back and menu icon. See attached screenshot.

Pixel 7 with latest OS and app updates.

![Screenshot_20230908-165334](https://github.com/ente-io/photos-app/assets/45749699/f06db53b-2d54-41e2-acc0-ceebdc03c464)

**Comment by Naveenchand06** [comment]
I want to fix this issue, could you please assign this to me?

**Comment by ashilkn** [comment]
> I want to fix this issue, could you please assign this to me?

Hi @Naveenchand06, sure you can take a look at this issue. I had tried fixing this couple of months back and figured it would take some refactoring and it wasn't worth the time. I can help you getting started.

**Comment by ashilkn** [comment]
> I want to fix this issue, could you please assign this to me?

Sure @Naveenchand06. From what I have observed this is only reproducible with phones that have a bigger status bar (in terms of height). For reproducing it otherwise, lower the height here. You can see the favourite icon getting unaligned from the rest of the icons.

https://github.com/ente-io/photos-app/blob/06c6c1ba4b8b2029e58fd4a1b37d6ee80a96db36/lib/ui/viewer/file/file_app_bar.dart#L88C53-L88C53

If you can somehow get the favourite icon to be always aligned with the other icons when changing the height, it should solve the issue i think.

You can find the use of `FavoriteWidget` in `file_app_bar.dart`.

**Comment by Naveenchand06** [comment]
Thank you @ashilkn! 
I'll check if I have any doubts. I'll let you know

**Comment by Naveenchand06** [comment]
Hi @ashilkn, 
I'm able to reproduce the issue by reducing the height.

When reducing the height, the Favourite widget moves to the top but the popup menu button and back arrow are in the same place. 
The Favourite widget is from a third-party package and does not behave like an IconButton. To make it work, I wrapped it with an IconButton and set its onPressed to null. This resolved the issue.

Please let me know if this is acceptable.

**Comment by ashilkn** [comment]
@Naveenchand06
Good job finding a workaround for it! Sounds fine, do create a PR for it :)

**Comment by Naveenchand06** [comment]
Here is the PR 

https://github.com/ente-io/photos-app/pull/1433

**Comment by BuzzKnightbeer** [comment]
Not sure if this is related, but on the desktop app the icons are all wonky and unaligned as well. Albeit not as extreme.
![Screenshot 2023-10-10 094301](https://github.com/ente-io/photos-app/assets/45749699/462548ca-18ea-40b4-9cd3-2868ed2d2db5)
