### ISSUE TITLE
Location search for countries and popular cities

### ISSUE THREAD

**Issue by beancaper** [ente-io/photos-app#1432]
Please add the option to show geolocation info in the app instead of having to manually add location. Having photos taken in the same city automatically grouped under a heading like “London, England” would also be nice.

**Comment by vishnukvmd** [comment]
Hey @beancaper, we're figuring out a privacy-friendly way to add this. In the meanwhile, could you please try using Location Tags – [ente.io/blog/location-tags](https://ente.io/blog/location-tags) ?

**Comment by beancaper** [comment]
Hi @vishnukvmd, thanks for responding! I just switched over to Ente from Google Photos, so I have tons of untagged, uncategorized travel photos that I just relied on Google to sort by location for me. I'd rather not go through all of them to manually add location.

I'm happy to wait patiently for Ente to develop a similar feature, though.

**Comment by vishnukvmd** [comment]
Hey, to be clear, you only have to create a tag for the locations you care about (not each photo). Once you tag a location and define a radius, the photos will cluster themselves.

But yes, we'd like to avoid the tagging step as well, at least for popular cities. We'll figure something out in our future updates.

**Comment by vishnukvmd** [comment]
You can now search for popular cities, across both mobile and web.

Country search is trickier, since it requires us to have geo-fencing data to correctly attribute a geo-location to a country.

I will close this issue for now, since an important use case has been taken care of.

I've created a new request for country search here: https://github.com/ente-io/ente/discussions/890
