### ISSUE TITLE
Video sound layering in memories

### ISSUE THREAD

**Issue by orangesunny** [ente-io/photos-app#1528]
**Describe the bug**
If I swipe through a memory where there are two or more videos subsequently, the sound of them play over each other, making user crazy.

**To Reproduce**
1. Open a memory in the app
2. Swipe through multiple videos in the memory
3. Hear the sound of multiple videos layering over each other
4. Get crazy

**Expected behavior**
Playback of a video, together with its sound, ends instantly once I swipe away from such video.

**Screenshots**
n/a

**Smartphone (please complete the following information):**
 - Device: Samsung S21
 - OS: Android 13, OneUI 5.1
 - App Version latest FDroid, 0.7.116 (why is FDroid version behind Google Play version?)

**Additional context**

**Comment by ua741** [comment]
Hey @orangesunny,

This issue should be fixed in the upcoming release (v0.8.1).

Regarding `why is FDroid version behind Google Play version?`: 
F-Droid build servers can take 3-5 days from the time a r[elease tag ](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/io.ente.photos.fdroid.yml)is pushed until the build is available for end customers. Unfortunately, this means that there will always be some lag before the update is available on F-Droid.

**Comment by orangesunny** [comment]
Thank you, @ua741, for the informative reply and amazing response time! It made me happy while I am filling the storage :)
