### ISSUE TITLE
Download an album + Capture date

### ISSUE THREAD

**Issue by REEKOON99** [ente-io/photos-app#1581]
I have two main complaints,

**first**: Why can't I download an entire album? I want to be able to download an entire album at once, and for the downloaded images to be in the same album name as the original album, not in the Downloads album. 

**This is the main reason why I would use a photo backup program and synchronize albums and photos between devices**.

**Secondly**, maintaining the original capture date of an image upon download is crucial for accurate organization and archival purposes. Preserving the date the photo was taken, rather than the date it was downloaded, ensures a more meaningful and chronological arrangement of your photo library.

**Comment by vishnukvmd** [comment]
Hey @REEKOON99, we're tracking the first issue to support bulk downloads @ https://github.com/ente-io/photos-app/issues/809.

Once we handle this, we will figure out how to render the original capture time instead of the file-download time. Thanks for sharing this feedback, we'll keep it it mind while implementing this feature.

For now I'll close this in favor of the original issue that is already on our roadmap. If you have any more thoughts, feel free to reopen!
