### ISSUE TITLE
Shared stories / memories

### ISSUE THREAD

**Issue by ph00lt0** [ente-io/photos-app#1622]
Shared albums do not appear in the stories / memories section. I request that they will also be shown there. Often I share photos with people who were at the same event, trip, etc. Would be nice if they can also get the photo's as memories.

**Comment by vishnukvmd** [comment]
Hey, from the code and a bit of testing, it looks like we're already showing shared photos and videos within Memories.

It's possible that the app has cached the items to be rendered within this widget. In which case, a restart should reflect the correct state.

Please reopen the issue if otherwise!

**Comment by vishnukvmd** [comment]
The code is not checking for any constraints about the ownership of the file

https://github.com/ente-io/photos-app/blob/c25212d9d8f85156053661c1b7194d5e42c9cfa9/lib/services/memories_service.dart#L109-L113

But if this seems reproducible, without bulk sharing, do let us know! 😬
