### ISSUE TITLE
"Hide from recents" does not prevent screenshots on Android

### ISSUE THREAD

**Issue by SkypLabs** [ente-io/photos-app#708]
Hi,

The "Hide from recents" security option is supposed to prevent screenshots, but it does not work on my system:

Phone model: Pixel 3a
OS: GrapheneOS
Android version: 12
Ente Photos version: 0.6.74 (F-Droid)

Let me know what other information you would need to investigate the issue.

**Comment by vishnukvmd** [comment]
Hey, thanks for reporting this!

Preventing screenshots was an unintended side effect that we wanted to warn our users about. The only outcome we wanted was to hide the app from the task-switcher.

Now I just tested the latest build on the two devices I have at hand (Android 10, Android 13), and it did prevent capturing of screenshots. But since Graphene is not blocking it, this is perhaps a ROM specific behavior, so will change the copy to reflect this.

Thanks for bringing this to our attention!

**Comment by SkypLabs** [comment]
Screenshots are correctly blocked on Signal and similar apps on GrapheneOS. I don't know why it's not the case here with Ente Photos and Auth.

@thestinger Any insights would be welcome :slightly_smiling_face:

**Comment by vishnukvmd** [comment]
> Screenshots are correctly blocked on Signal and similar apps on GrapheneOS. I don't know why it's not the case here with Ente Photos and Auth.
> 
> 
> 
> @thestinger Any insights would be welcome :slightly_smiling_face: 

After reading through the documentation further, we'll have to pass this flag per screen to achieve the desired effect (across all ROMs, including Graphene). Will figure.

**Comment by vishnukvmd** [comment]
Hey! After discussing this internally, we realized that this is an obscure feature that has been made redundant by our Lock Screen.

In the interest of reducing complexity, we have decided to remove this half broken setting: https://github.com/ente-io/photos-app/pull/792.

Thank you for bringing this to our attention! 🙏
